name: uniqtrack
description: "A tracking mobile application."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.2.7
  go_router_paths: ^0.2.2
  intl: ^0.19.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  gap: ^3.0.1
  image_picker: ^1.1.2
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  provider: ^6.1.2
  formz: ^0.7.0
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  firebase_storage: ^12.2.0
  uuid: ^4.5.0
  cloud_firestore: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/placeholders/

flutter_intl:
  enabled: true
